### ISSUE TITLE
ENOENT, no such file or directory

### ISSUE THREAD

**Issue by athtest800** [capriza/jxcore-android-sample#3]
I have the following isssue.
Could you help?

```
E/jxcore-log: ENOENT, no such file or directory '/data/data/com.android.jxcore.jxcoresample/files/someModule.js'
```

**Comment by athtest800** [comment]
All GOOD!!!
I used another device and it works. Thanks!

**Comment by oriharel** [comment]
Probably related to Android 6.0 changing the file system structure. I'll fix it.

**Comment by athtest800** [comment]
Yes, it happens on Android 6.

**Comment by okhiroyuki** [comment]
@oriharel How did you fix it?
