### ISSUE TITLE
ndk build failed

### ISSUE THREAD

**Issue by wtchaos** [capriza/jxcore-android-sample#6]
Hello
I get the error when run the app
`finished with non-zero exit value 2`
I add the ndk.dir=.../android-ndk-r17 to the local.properties
Could you help me?How can I fix it?
Thank you!

**Comment by fujifish** [comment]
JXCore is deprecated, we no longer maintain this example.
Take look at https://github.com/jxcore/jxcore

> Important Notice:
> Nubisa halting active development on JXcore platform
